### ISSUE TITLE
Resource Exhaustion Error When Replacing 'C' with 'Fe' in Example Script

### ISSUE THREAD

**Issue by mwkskt** [bytedance/LapNet#3]
## Description of Error
I ran the following command:
```bash
python3 main.py --config lapnet/configs/atom.py --config.system.atom Fe
```
The script `lapnet/configs/atom.py` is included in this repository. I encountered the following error:
```
Traceback (most recent call last):
  File "/home/s2410058/ichibha/LapNet/main.py", line 50, in <module>
    app.run(main)
  File "/home/s2410058/kagayaki/packages/anaconda3/envs/nnqmc/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/s2410058/kagayaki/packages/anaconda3/envs/nnqmc/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/s2410058/ichibha/LapNet/main.py", line 46, in main
    train.train(cfg)
  File "/home/s2410058/ichibha/LapNet/lapnet/train.py", line 580, in train
    initial_energy, _ = ptotal_energy(params, subkeys, data)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE EXHAUSTED: Out of memory while trying to allocate 63357884960 bytes.
```

## Question
I discovered that this issue is due to GPU memory exhaustion, which seems unlikely for a single atom calculation. There were no errors when I performed the command with carbon. Are there any adjustments needed to run it for iron?

## System Configuration
I used half the resources of the following node:

- **CPU:** Intel Xeon GOLD 5320 2.2GHz 26Core x2 Sockets: 52Cores
- **Memory:** DDR4/3200 SDRAM x16 : 512GB
- **GPU:** NVIDIA A40 x 2
- **Node:** 20 Nodes
- More details at [JAIST MPC Kagayaki](https://www.jaist.ac.jp/iscenter/en/mpc/kagayaki/)

## Installation Steps of NNVMC
```bash
module purge
module load cuda/11.8

conda create --name nnqmc python=3.9
conda activate nnqmc

pip install jax==0.3.25
pip install jaxlib==0.3.25+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

pip install git+https://github.com/YWolfeee/lapjax.git

cd LapNet
pip install -e .
```

## Python Packages
These are the Python libraries:
```bash
python3 -m pip freeze
    absl-py==1.4.0
    astunparse==1.6.3
    attrs==21.2.0
    cachetools==5.3.3
    certifi==2024.2.2
    charset-normalizer==3.3.2
    chex==0.1.5
    cloudpickle==3.0.0
    contextlib2==21.6.0
    contourpy==1.2.1
    cycler==0.12.1
    decorator==5.1.1
    distrax==0.1.3
    dm-haiku==0.0.9
    dm-tree==0.1.8
    flatbuffers==24.3.25
    flax==0.6.1
    fonttools==4.51.0
    gast==0.4.0
    google-auth==2.29.0
    google-auth-oauthlib==0.4.6
    google-pasta==0.2.0
    grpcio==1.62.2
    gviz-api==1.10.0
    h5py==3.8.0
    idna==3.7
    immutabledict==4.2.0
    importlib_metadata==7.1.0
    importlib_resources==6.4.0
    jax==0.3.25
    jaxlib==0.3.25+cuda11.cudnn82
    jmp==0.0.4
    keras==2.11.0
    Keras-Preprocessing==1.1.2
    kfac-jax==0.0.3
    kiwisolver==1.4.5
    lapjax @ git+https://github.com/YWolfeee/lapjax.git@f50f734d6f289c468264835f36fc4f9cc6667db0
    -e git+https://github.com/bytedance/LapNet.git@7ec19b019376d9458137c85a817ecae1036ac00f#egg=lapnet
    libclang==18.1.1
    Markdown==3.6
    markdown-it-py==3.0.0
    MarkupSafe==2.1.5
    matplotlib==3.8.4
    mdurl==0.1.2
    ml-collections==0.1.1
    ml-dtypes==0.3.2
    msgpack==1.0.8
    namex==0.0.8
    numexpr==2.10.0
    numpy==1.21.5
    oauthlib==3.2.2
    opt-einsum==3.3.0
    optax==0.1.4
    optree==0.11.0
    packaging==24.0
    pandas==1.3.5
    pillow==10.3.0
    protobuf==3.19.6
    pyasn1==0.6.0
    pyasn1_modules==0.4.0
    pyblock==0.6
    Pygments==2.17.2
    pyparsing==3.1.2
    pyscf==2.1.1
    python-dateutil==2.9.0.post0
    pytz==2024.1
    PyYAML==6.0.1
    requests==2.31.0
    requests-oauthlib==2.0.0
    rich==13.7.1
    rsa==4.9
    scipy==1.7.3
    six==1.16.0
    tables==3.7.0
    tabulate==0.9.0
    tensorboard==2.11.2
    tensorboard-data-server==0.6.1
    tensorboard-plugin-wit==1.8.1
    tensorboard_plugin_profile==2.15.1
    tensorflow==2.11.1
    tensorflow-estimator==2.11.0
    tensorflow-io-gcs-filesystem==0.36.0
    tensorflow-probability==0.24.0
    termcolor==2.4.0
    toolz==0.12.1
    typing_extensions==4.5.0
    urllib3==2.2.1
    Werkzeug==3.0.2
    wrapt==1.14.1
    zipp==3.18.1
```
I confirmed that the library dependencies are fine.
```bash
pip check
No broken requirements found.
```

**Comment by WeiluoRen-ByteDance** [comment]
It seems your GPUs don't have enough memory for the studied system, hinted by the `RESOURCE EXHAUSTED: Out of memory while trying to allocate 63357884960 bytes.` part in the error message.

One way to confirm that is to use a (much) smaller batch size and see if the issue persists. You can try adding an additional flag `--config.batch_size 16` to adjust the batch size from 4096 (the default value) to 16. 

Let me know how it goes :)

**Comment by mwkskt** [comment]
Thank you for your advice.

As you suggested, I lowered the batch size and it worked perfectly.
I really appreciate your help.
